### ISSUE TITLE
Invalid transformation for global const variables

### ISSUE THREAD

**Issue by sithhell** [allscale/allscale_compiler#10]
The compiler currently transforms code like this:
```
namespace { const T t = {...}; }
```
into code like this:
```
namespace { const T t; } int IMP_main() { new (&t) T{...}; }
```

This is undefined and leads to runtime errors since `t` might be placed in a read only segment of the binary.

**Comment by destructor64** [comment]
Fixed with insieme commit https://github.com/insieme/insieme/commit/d78fb2e4cb9f9bd81162426268a818063556a098
