### ISSUE TITLE
quickstart installs outdated llvm 3.6 compiler 

### ISSUE THREAD

**Issue by schloegl** [allscale/allscale_compiler#11]
When following the quickstart instructions of allscale, the installer pulls in and tries to install llvm3.6, although my system does already provide llvm-3.8. The installer should check and use this more recent version of llvm.

**Comment by W4RH4WK** [comment]
Hey there, please note that even if your system package manager would provide llvm 3.6 we could not use it as we require a few patches for it to work. The installer does apply them prior compilation.

We know that this is an inconvenience in the setup process but at the moment there is no way around it. Do you have any issues with version 3.6 being used?

**Comment by W4RH4WK** [comment]
For llvm there is only a single patch. It can be found [here](https://github.com/insieme/insieme/blob/master/scripts/dependencies/patches/llvm-0001-insieme-clang.patch).
