### ISSUE TITLE
Error when building current master

### ISSUE THREAD

**Issue by sithhell** [allscale/allscale_compiler#5]
I just pulled the recent changes from master and now I am getting a compiler error:
```
[14 of 62] Compiling Insieme.Inspire.IR.NodeKind ( src/Insieme/Inspire/IR/NodeKind.hs, /home/heller/projects/allscale_compiler/build/insieme/analysis/src/cba/haskell/insieme-hat/dist-newstyle/build/x86_64-linux/ghc-8.0.2/insieme-hat-0.2/build/Insieme/Inspire/IR/NodeKind.o )

src/Insieme/Inspire/IR/NodeKind.hs:112:12: error:
    Not in scope: data constructor ‘StaticMemberFunction’

src/Insieme/Inspire/IR/NodeKind.hs:113:12: error:
    Not in scope: data constructor ‘StaticMemberFunctions’
```

On the master branch, I did a `git pull --rebase --recurse-submodules=yes`. Is there anything I miss?

**Comment by sithhell** [comment]
The commit hashes of the submodule seem to be correct.

**Comment by destructor64** [comment]
There was a change which breaks the haskell dependencies. you could clean that, but easiest ist cleaning the whole build dir...

**Comment by sithhell** [comment]
Just removing the `insieme` directory from the build tree seems to fix that problem. No need to clean the whole build dir, as it seems.
Thanks for the pointer.
