### ISSUE TITLE
`DataItemManager::get` is not supposed be used in tight loops

### ISSUE THREAD

**Issue by sithhell** [allscale/allscale_compiler#7]
The compiler currently generates code with data items that look similar to that:
https://github.com/allscale/allscale_runtime/blob/master/tests/performance/data_item_get.cpp#L84

The problem here is, that calls to `DataItemManager::get` does incur some overhead which the (backend) compiler is not able to optimize (this is related to accesses to a global object which requires to acquire a mutex). As such, when data items are used in tight loops, this generates significant overheads.
Those overheads should be possible to avoid, since the `DataItemManager::get` calls are mostly loop invariants.
This can be seen by comparing to: https://github.com/allscale/allscale_runtime/blob/master/tests/performance/data_item_get_invariant.cpp#L85

Initial tests show, that the invariant version is about 40 times faster.

**Comment by destructor64** [comment]
This has been implemented with commits https://github.com/allscale/allscale_compiler/commit/80f24363664c16e725dc976bc0daefdb52c75ea5 https://github.com/allscale/allscale_compiler/commit/127d8ff74b9d7868e473ff1a859c8dd51b90345b https://github.com/allscale/allscale_compiler/commit/9808f3b13cd95b3641e708aa42323afcae51ea89 https://github.com/allscale/allscale_compiler/commit/ac40d551b41f4b82ce43b699be497c6321e2e42c in february,
